// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraineeTracker.Data;

#nullable disable

namespace TraineeTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711131024_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("FeedbackRead", b =>
                {
                    b.Property<int>("FeedbackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReaderId")
                        .HasColumnType("TEXT");

                    b.HasKey("FeedbackId", "ReaderId");

                    b.HasIndex("ReaderId");

                    b.ToTable("FeedbackRead");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeachingPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TraineeEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TraineeStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TeachingPlanId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.EmailNotificationSetting", b =>
                {
                    b.Property<int>("EmailNotificationSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveAcceptedNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveFinishedNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveImportChangeNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveOpenNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveRatedNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveRejectedNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveSkippedNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveStartedNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmailNotificationSettingsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmailNotificationSettings");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HoursOfEffort")
                        .HasColumnType("REAL");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousKnowledge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FeedbackId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LessonId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EstimatedEffort")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MakandraId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortingIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LessonId");

                    b.HasIndex("TeachingPlanId");

                    b.HasIndex("MakandraId", "TeachingPlanId")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.ProcessingPause", b =>
                {
                    b.Property<int>("ProcessingPauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraineeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessingPauseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("ProcessingPauses");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TeachingPlan", b =>
                {
                    b.Property<int>("TeachingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeachingPlanId");

                    b.ToTable("TeachingPlans");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TraineeLesson", b =>
                {
                    b.Property<int>("TraineeLessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DayFinished")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DayStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TraineeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TraineeLessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("TraineeId");

                    b.ToTable("TraineeLessons");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TraineeLessonLogEntry", b =>
                {
                    b.Property<int>("TraineeLessonLogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeLessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TraineeLessonLogEntryId");

                    b.ToTable("TraineeLessonLogEntries");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TraineeStatisticsSnapshot", b =>
                {
                    b.Property<int>("TraineeStatisticsSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DaysPresentTillToday")
                        .HasColumnType("REAL");

                    b.Property<double?>("DaysPresentTotal")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsUpToDate")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LessonDaysBuffer")
                        .HasColumnType("REAL");

                    b.Property<double?>("LessonDaysCompleted")
                        .HasColumnType("REAL");

                    b.Property<double?>("LessonDaysOpen")
                        .HasColumnType("REAL");

                    b.Property<double?>("PredictedMissingActualDays")
                        .HasColumnType("REAL");

                    b.Property<double?>("PredictedMissingEstimatedEffortAtEnd")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("SnapshotDateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.Property<string>("TraineeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TraineeStatisticsSnapshotId");

                    b.HasIndex("TraineeId")
                        .IsUnique();

                    b.ToTable("TraineeStatisticsSnapshots");
                });

            modelBuilder.Entity("FeedbackRead", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.Feedback", null)
                        .WithMany()
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.ApplicationUser", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", null)
                        .WithMany("LastSelectedTrainees")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("TraineeTracker.Models.Domain.TeachingPlan", "TeachingPlan")
                        .WithMany("Trainees")
                        .HasForeignKey("TeachingPlanId");

                    b.Navigation("TeachingPlan");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.EmailNotificationSetting", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", "User")
                        .WithOne("EmailNotificationSetting")
                        .HasForeignKey("TraineeTracker.Models.Domain.EmailNotificationSetting", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.Feedback", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", "Author")
                        .WithMany("WrittenFeedbacks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeTracker.Models.Domain.Lesson", "Lesson")
                        .WithMany("Feedbacks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.Lesson", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.TeachingPlan", "TeachingPlan")
                        .WithMany("Lessons")
                        .HasForeignKey("TeachingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeachingPlan");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.ProcessingPause", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", "Trainee")
                        .WithMany("ProcessingPauses")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TraineeLesson", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.Lesson", "Lesson")
                        .WithMany("TraineeLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", "Trainee")
                        .WithMany("TraineeLessons")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TraineeStatisticsSnapshot", b =>
                {
                    b.HasOne("TraineeTracker.Models.Domain.ApplicationUser", "Trainee")
                        .WithOne("TraineeStatisticsSnapshot")
                        .HasForeignKey("TraineeTracker.Models.Domain.TraineeStatisticsSnapshot", "TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.ApplicationUser", b =>
                {
                    b.Navigation("EmailNotificationSetting")
                        .IsRequired();

                    b.Navigation("LastSelectedTrainees");

                    b.Navigation("ProcessingPauses");

                    b.Navigation("TraineeLessons");

                    b.Navigation("TraineeStatisticsSnapshot");

                    b.Navigation("UserRoles");

                    b.Navigation("WrittenFeedbacks");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.Lesson", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("TraineeLessons");
                });

            modelBuilder.Entity("TraineeTracker.Models.Domain.TeachingPlan", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
