services:
  traineetracker:
    image: gitlab.isse.de:5050/lehre/sopro/2025-sose/gruppen/team-07/traineetracker
    container_name: traineetracker
    ports:
      - "5000:5000"
    volumes:
      - traineetracker_data:/TraineeTracker/persistence
    restart: always

volumes:
  traineetracker_data: